client_config_backend: settings
client_config:
  client_id: 38788626384-i5dpaat5athtj8iikfkolo6pqid64uji.apps.googleusercontent.com
  client_secret: 6q1a73zLulEO_IBCs79bKsL3

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install